### ISSUE TITLE
重启 Mirai 后会清空订阅

### ISSUE THREAD

**Issue by timeance** [nitezs/RssBot#3]
设置了订阅后，如果重启 Mirai 会导致订阅清空

Mirai `v2.9.0-M1`
RssBot `v2.0`

**Comment by nitezs** [comment]
订阅数据保存在 \data\RssBot 文件夹下，重启不会删除的

**Comment by timeance** [comment]
> 

刚刚检查了一下订阅数据  \data\RssBot\data.json 是空的...
使用命令 #listall 也提示无订阅了

**Comment by nitezs** [comment]
> > 
> 
> 刚刚检查了一下订阅数据 \data\RssBot\data.json 是空的... 使用命令 #listall 也提示无订阅了

可能是误操作导致的，我测试没啥问题

**Comment by timeance** [comment]
好的，非常感谢
